
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: PaperBin Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup paper
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/setup.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/setup.sh"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for build script
      run: chmod +x build.sh
    - name: Build
      run: ./build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: paperbin
        path: ./build/libs/*
